### ISSUE TITLE
Implementar busca <OR>

### ISSUE THREAD

**Issue by nymarya** [GabrielArSouza/BuscaIndexada#18]
#O programa deverá retornar todas as ocorrências em que pelo
menos uma das palavras-chave seja encontrada.

Exemplo: "computador"
```
microsoft.txt:​ ​ ​ 1 ​ ​ ocorrência​ ​ da​ ​ palavra​ ​ ‘computador’​ ​ na​ ​ linha​ ​ 1
apple.txt:​ ​ ​ 1 ​ ​ ocorrência​ ​ da​ ​ palavra​ ​ ‘computador’​ ​ na​ ​ linha​ ​ 1
```

**Comment by gbrsouza** [comment]
ainda falta ordenar, mas é melhor colocar outra tarefa
